/**
 * DEV API
 * Access DEV articles, comments and other resources via API  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * OpenAPI spec version: 0.5.7
 * Contact: yo@dev.to
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */import { ArticleFlareTag } from './articleFlareTag';
import { ArticleOrganization } from './articleOrganization';
import { ArticleUser } from './articleUser';


export interface ArticleMe { 
    _typeOf: string;
    id: number;
    title: string;
    description: string;
    coverImage: string;
    published: boolean;
    publishedAt: Date;
    tagList: Array<string>;
    slug: string;
    path: string;
    url: string;
    canonicalUrl: string;
    commentsCount: number;
    positiveReactionsCount: number;
    pageViewsCount: number;
    /**
     * Crossposting or published date time
     */
    publishedTimestamp: Date;
    user: any;
    organization?: any;
    flareTag?: any;
}