/**
 * DEV API
 * Access DEV articles, comments and other resources via API  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * OpenAPI spec version: 0.5.7
 * Contact: yo@dev.to
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */import { ArticleUser } from './articleUser';


export interface ArticleShow { 
    _typeOf: string;
    id: number;
    title: string;
    description: string;
    coverImage: string;
    readablePublishDate: string;
    socialImage: string;
    tagList: string;
    tags: Array<string>;
    slug: string;
    path: string;
    url: string;
    canonicalUrl: string;
    commentsCount: number;
    positiveReactionsCount: number;
    createdAt: Date;
    editedAt: Date;
    crosspostedAt: Date;
    publishedAt: Date;
    lastCommentAt: Date;
    bodyHtml: string;
    bodyMarkdown: string;
    user: any;
}